version: "3.9"

services:

  fluentd:
    container_name: efk_fluentd
    build:
      context: ./fluentd
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      - efk-net
    volumes:
      - ./volumes/fluentd/fluent.conf:/fluentd/etc/fluent.conf

  elasticsearch:
    container_name: efk_elasticsearch
    image: elasticsearch:8.8.0
    expose:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./volumes/es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    networks:
      - efk-net

  kibana:
    container_name: efk_kibana
    image: kibana:8.8.0
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - TZ=Europe/Warsaw
      # - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
    volumes:
      - ./volumes/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - efk-net

  log-generator:
    container_name: efk_log-generator
    hostname: log-generator
    image: busybox
    command: /bin/sh -c "while true; do echo \"Log message at $(date)\"; sleep 1; done"
    depends_on:
      - fluentd
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224


volumes:
  esdata:
    name: esdata

networks:
  efk-net:
    name: efk-net
